### ISSUE TITLE
Adding group informix ID:200 failed

### ISSUE THREAD

**Issue by debu66er** [0x1fff/docker-informix#3]
Hi, I am following your steps using as host Ubuntu 15.04 and Docker 1.9.0
When executing informix_install.sh it always fails when adding the group with error:
`Adding group informix ID:200 failed`
It doesn't matter if I use Debian or Ubuntu in Dockerfile. Always same error.

Reading Internet I found it could be related to SELinux (which theoretically I have disabled) or issues on Ubuntu hosting machines: [http://www.fewbytes.com/docker-selinux-and-the-myth-of-kernel-indipendence/](http://www.fewbytes.com/docker-selinux-and-the-myth-of-kernel-indipendence/) but you used Ubuntu and it is working for you.
Have you seen this before or do you have any tip?

**Comment by debu66er** [comment]
BTW, if I just start debian:wheezy or ubuntu:14.04 containers in interactive mode and I execute:
`groupadd informix -g 200`
the command works fine.
If I add it as a RUN line in the Dockerfile, the command also works fine.
 So it seems the issue is when executing it from RUN bash ./informix_install.sh

**Comment by 0x1fff** [comment]
Hello, sorry for late reply, I didn't receive notification about bug. 
I have read your description and I probably found the source of bug in `informix_install.sh`. 
There was a wrong usage of function `myfatal` now it should work fine ... could you make retest?

**Comment by debu66er** [comment]
It worked. Thank you very much.
